// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keypair.proto

package phe

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Keypair struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Keypair) Reset()         { *m = Keypair{} }
func (m *Keypair) String() string { return proto.CompactTextString(m) }
func (*Keypair) ProtoMessage()    {}
func (*Keypair) Descriptor() ([]byte, []int) {
	return fileDescriptor_40535d21a2c7da09, []int{0}
}

func (m *Keypair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keypair.Unmarshal(m, b)
}
func (m *Keypair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keypair.Marshal(b, m, deterministic)
}
func (m *Keypair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keypair.Merge(m, src)
}
func (m *Keypair) XXX_Size() int {
	return xxx_messageInfo_Keypair.Size(m)
}
func (m *Keypair) XXX_DiscardUnknown() {
	xxx_messageInfo_Keypair.DiscardUnknown(m)
}

var xxx_messageInfo_Keypair proto.InternalMessageInfo

func (m *Keypair) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Keypair) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Keypair)(nil), "phe.Keypair")
}

func init() { proto.RegisterFile("keypair.proto", fileDescriptor_40535d21a2c7da09) }

var fileDescriptor_40535d21a2c7da09 = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4e, 0xad, 0x2c,
	0x48, 0xcc, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0xc8, 0x48, 0x55, 0x72,
	0xe7, 0x62, 0xf7, 0x86, 0x88, 0x0a, 0xc9, 0x70, 0x71, 0x16, 0x94, 0x26, 0xe5, 0x64, 0x26, 0x7b,
	0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x21, 0x04, 0x84, 0xe4, 0xb8, 0xb8, 0x0a,
	0x8a, 0x32, 0xcb, 0x12, 0x4b, 0x52, 0x41, 0xd2, 0x4c, 0x60, 0x69, 0x24, 0x91, 0x24, 0x36, 0xb0,
	0xa1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x37, 0x8b, 0x23, 0x65, 0x00, 0x00, 0x00,
}
