// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phe.proto

package phe

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Keypair struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Keypair) Reset()         { *m = Keypair{} }
func (m *Keypair) String() string { return proto.CompactTextString(m) }
func (*Keypair) ProtoMessage()    {}
func (*Keypair) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f30d920d9c0b48, []int{0}
}

func (m *Keypair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keypair.Unmarshal(m, b)
}
func (m *Keypair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keypair.Marshal(b, m, deterministic)
}
func (m *Keypair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keypair.Merge(m, src)
}
func (m *Keypair) XXX_Size() int {
	return xxx_messageInfo_Keypair.Size(m)
}
func (m *Keypair) XXX_DiscardUnknown() {
	xxx_messageInfo_Keypair.DiscardUnknown(m)
}

var xxx_messageInfo_Keypair proto.InternalMessageInfo

func (m *Keypair) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Keypair) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

type EnrollmentRecord struct {
	Ns                   []byte   `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Nc                   []byte   `protobuf:"bytes,2,opt,name=nc,proto3" json:"nc,omitempty"`
	T0                   []byte   `protobuf:"bytes,3,opt,name=t0,proto3" json:"t0,omitempty"`
	T1                   []byte   `protobuf:"bytes,4,opt,name=t1,proto3" json:"t1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentRecord) Reset()         { *m = EnrollmentRecord{} }
func (m *EnrollmentRecord) String() string { return proto.CompactTextString(m) }
func (*EnrollmentRecord) ProtoMessage()    {}
func (*EnrollmentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f30d920d9c0b48, []int{1}
}

func (m *EnrollmentRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentRecord.Unmarshal(m, b)
}
func (m *EnrollmentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentRecord.Marshal(b, m, deterministic)
}
func (m *EnrollmentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentRecord.Merge(m, src)
}
func (m *EnrollmentRecord) XXX_Size() int {
	return xxx_messageInfo_EnrollmentRecord.Size(m)
}
func (m *EnrollmentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentRecord proto.InternalMessageInfo

func (m *EnrollmentRecord) GetNs() []byte {
	if m != nil {
		return m.Ns
	}
	return nil
}

func (m *EnrollmentRecord) GetNc() []byte {
	if m != nil {
		return m.Nc
	}
	return nil
}

func (m *EnrollmentRecord) GetT0() []byte {
	if m != nil {
		return m.T0
	}
	return nil
}

func (m *EnrollmentRecord) GetT1() []byte {
	if m != nil {
		return m.T1
	}
	return nil
}

type ProofOfSuccess struct {
	Term1                []byte   `protobuf:"bytes,1,opt,name=term1,proto3" json:"term1,omitempty"`
	Term2                []byte   `protobuf:"bytes,2,opt,name=term2,proto3" json:"term2,omitempty"`
	Term3                []byte   `protobuf:"bytes,3,opt,name=term3,proto3" json:"term3,omitempty"`
	BlindX               []byte   `protobuf:"bytes,4,opt,name=blind_x,json=blindX,proto3" json:"blind_x,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofOfSuccess) Reset()         { *m = ProofOfSuccess{} }
func (m *ProofOfSuccess) String() string { return proto.CompactTextString(m) }
func (*ProofOfSuccess) ProtoMessage()    {}
func (*ProofOfSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f30d920d9c0b48, []int{2}
}

func (m *ProofOfSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofOfSuccess.Unmarshal(m, b)
}
func (m *ProofOfSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofOfSuccess.Marshal(b, m, deterministic)
}
func (m *ProofOfSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofOfSuccess.Merge(m, src)
}
func (m *ProofOfSuccess) XXX_Size() int {
	return xxx_messageInfo_ProofOfSuccess.Size(m)
}
func (m *ProofOfSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofOfSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_ProofOfSuccess proto.InternalMessageInfo

func (m *ProofOfSuccess) GetTerm1() []byte {
	if m != nil {
		return m.Term1
	}
	return nil
}

func (m *ProofOfSuccess) GetTerm2() []byte {
	if m != nil {
		return m.Term2
	}
	return nil
}

func (m *ProofOfSuccess) GetTerm3() []byte {
	if m != nil {
		return m.Term3
	}
	return nil
}

func (m *ProofOfSuccess) GetBlindX() []byte {
	if m != nil {
		return m.BlindX
	}
	return nil
}

type ProofOfFail struct {
	Term1                []byte   `protobuf:"bytes,1,opt,name=term1,proto3" json:"term1,omitempty"`
	Term2                []byte   `protobuf:"bytes,2,opt,name=term2,proto3" json:"term2,omitempty"`
	Term3                []byte   `protobuf:"bytes,3,opt,name=term3,proto3" json:"term3,omitempty"`
	Term4                []byte   `protobuf:"bytes,4,opt,name=term4,proto3" json:"term4,omitempty"`
	BlindA               []byte   `protobuf:"bytes,5,opt,name=blind_a,json=blindA,proto3" json:"blind_a,omitempty"`
	BlindB               []byte   `protobuf:"bytes,6,opt,name=blind_b,json=blindB,proto3" json:"blind_b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofOfFail) Reset()         { *m = ProofOfFail{} }
func (m *ProofOfFail) String() string { return proto.CompactTextString(m) }
func (*ProofOfFail) ProtoMessage()    {}
func (*ProofOfFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f30d920d9c0b48, []int{3}
}

func (m *ProofOfFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofOfFail.Unmarshal(m, b)
}
func (m *ProofOfFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofOfFail.Marshal(b, m, deterministic)
}
func (m *ProofOfFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofOfFail.Merge(m, src)
}
func (m *ProofOfFail) XXX_Size() int {
	return xxx_messageInfo_ProofOfFail.Size(m)
}
func (m *ProofOfFail) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofOfFail.DiscardUnknown(m)
}

var xxx_messageInfo_ProofOfFail proto.InternalMessageInfo

func (m *ProofOfFail) GetTerm1() []byte {
	if m != nil {
		return m.Term1
	}
	return nil
}

func (m *ProofOfFail) GetTerm2() []byte {
	if m != nil {
		return m.Term2
	}
	return nil
}

func (m *ProofOfFail) GetTerm3() []byte {
	if m != nil {
		return m.Term3
	}
	return nil
}

func (m *ProofOfFail) GetTerm4() []byte {
	if m != nil {
		return m.Term4
	}
	return nil
}

func (m *ProofOfFail) GetBlindA() []byte {
	if m != nil {
		return m.BlindA
	}
	return nil
}

func (m *ProofOfFail) GetBlindB() []byte {
	if m != nil {
		return m.BlindB
	}
	return nil
}

type UpdateToken struct {
	A                    []byte   `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    []byte   `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateToken) Reset()         { *m = UpdateToken{} }
func (m *UpdateToken) String() string { return proto.CompactTextString(m) }
func (*UpdateToken) ProtoMessage()    {}
func (*UpdateToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f30d920d9c0b48, []int{4}
}

func (m *UpdateToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateToken.Unmarshal(m, b)
}
func (m *UpdateToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateToken.Marshal(b, m, deterministic)
}
func (m *UpdateToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateToken.Merge(m, src)
}
func (m *UpdateToken) XXX_Size() int {
	return xxx_messageInfo_UpdateToken.Size(m)
}
func (m *UpdateToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateToken.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateToken proto.InternalMessageInfo

func (m *UpdateToken) GetA() []byte {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *UpdateToken) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

type EnrollmentResponse struct {
	Ns                   []byte          `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	C0                   []byte          `protobuf:"bytes,2,opt,name=c0,proto3" json:"c0,omitempty"`
	C1                   []byte          `protobuf:"bytes,3,opt,name=c1,proto3" json:"c1,omitempty"`
	Proof                *ProofOfSuccess `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EnrollmentResponse) Reset()         { *m = EnrollmentResponse{} }
func (m *EnrollmentResponse) String() string { return proto.CompactTextString(m) }
func (*EnrollmentResponse) ProtoMessage()    {}
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f30d920d9c0b48, []int{5}
}

func (m *EnrollmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentResponse.Unmarshal(m, b)
}
func (m *EnrollmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentResponse.Marshal(b, m, deterministic)
}
func (m *EnrollmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentResponse.Merge(m, src)
}
func (m *EnrollmentResponse) XXX_Size() int {
	return xxx_messageInfo_EnrollmentResponse.Size(m)
}
func (m *EnrollmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentResponse proto.InternalMessageInfo

func (m *EnrollmentResponse) GetNs() []byte {
	if m != nil {
		return m.Ns
	}
	return nil
}

func (m *EnrollmentResponse) GetC0() []byte {
	if m != nil {
		return m.C0
	}
	return nil
}

func (m *EnrollmentResponse) GetC1() []byte {
	if m != nil {
		return m.C1
	}
	return nil
}

func (m *EnrollmentResponse) GetProof() *ProofOfSuccess {
	if m != nil {
		return m.Proof
	}
	return nil
}

type VerifyPasswordRequest struct {
	Ns                   []byte   `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	C0                   []byte   `protobuf:"bytes,2,opt,name=c0,proto3" json:"c0,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordRequest) Reset()         { *m = VerifyPasswordRequest{} }
func (m *VerifyPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordRequest) ProtoMessage()    {}
func (*VerifyPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f30d920d9c0b48, []int{6}
}

func (m *VerifyPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordRequest.Unmarshal(m, b)
}
func (m *VerifyPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordRequest.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordRequest.Merge(m, src)
}
func (m *VerifyPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordRequest.Size(m)
}
func (m *VerifyPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordRequest proto.InternalMessageInfo

func (m *VerifyPasswordRequest) GetNs() []byte {
	if m != nil {
		return m.Ns
	}
	return nil
}

func (m *VerifyPasswordRequest) GetC0() []byte {
	if m != nil {
		return m.C0
	}
	return nil
}

type VerifyPasswordResponse struct {
	Res                  bool            `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	C1                   []byte          `protobuf:"bytes,2,opt,name=c1,proto3" json:"c1,omitempty"`
	ProofSuccess         *ProofOfSuccess `protobuf:"bytes,3,opt,name=proof_success,json=proofSuccess,proto3" json:"proof_success,omitempty"`
	ProofFail            *ProofOfFail    `protobuf:"bytes,4,opt,name=proof_fail,json=proofFail,proto3" json:"proof_fail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VerifyPasswordResponse) Reset()         { *m = VerifyPasswordResponse{} }
func (m *VerifyPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordResponse) ProtoMessage()    {}
func (*VerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f30d920d9c0b48, []int{7}
}

func (m *VerifyPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordResponse.Unmarshal(m, b)
}
func (m *VerifyPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordResponse.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordResponse.Merge(m, src)
}
func (m *VerifyPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordResponse.Size(m)
}
func (m *VerifyPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordResponse proto.InternalMessageInfo

func (m *VerifyPasswordResponse) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func (m *VerifyPasswordResponse) GetC1() []byte {
	if m != nil {
		return m.C1
	}
	return nil
}

func (m *VerifyPasswordResponse) GetProofSuccess() *ProofOfSuccess {
	if m != nil {
		return m.ProofSuccess
	}
	return nil
}

func (m *VerifyPasswordResponse) GetProofFail() *ProofOfFail {
	if m != nil {
		return m.ProofFail
	}
	return nil
}

func init() {
	proto.RegisterType((*Keypair)(nil), "phe.Keypair")
	proto.RegisterType((*EnrollmentRecord)(nil), "phe.EnrollmentRecord")
	proto.RegisterType((*ProofOfSuccess)(nil), "phe.ProofOfSuccess")
	proto.RegisterType((*ProofOfFail)(nil), "phe.ProofOfFail")
	proto.RegisterType((*UpdateToken)(nil), "phe.UpdateToken")
	proto.RegisterType((*EnrollmentResponse)(nil), "phe.EnrollmentResponse")
	proto.RegisterType((*VerifyPasswordRequest)(nil), "phe.VerifyPasswordRequest")
	proto.RegisterType((*VerifyPasswordResponse)(nil), "phe.VerifyPasswordResponse")
}

func init() { proto.RegisterFile("phe.proto", fileDescriptor_36f30d920d9c0b48) }

var fileDescriptor_36f30d920d9c0b48 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0x94, 0x76, 0xe9, 0xb4, 0xac, 0x2a, 0xf3, 0x2f, 0x17, 0x04, 0xf2, 0x89, 0xbd,
	0x2c, 0xcd, 0x2e, 0x12, 0x5c, 0x41, 0x02, 0x09, 0xf5, 0xc0, 0x2a, 0xfc, 0x11, 0xb7, 0xca, 0x71,
	0x26, 0xda, 0xa8, 0x59, 0xdb, 0xd8, 0x2e, 0x90, 0x27, 0xe1, 0x09, 0x78, 0x4f, 0x14, 0x7b, 0x42,
	0x03, 0x02, 0x71, 0xd9, 0x9b, 0xbf, 0x19, 0x8f, 0xbf, 0x5f, 0xfc, 0x39, 0x30, 0x37, 0x97, 0x78,
	0x6a, 0xac, 0xf6, 0x9a, 0x4d, 0xcc, 0x25, 0xf2, 0x37, 0x70, 0xb4, 0xc1, 0xce, 0x88, 0xc6, 0xb2,
	0x07, 0x00, 0x66, 0x5f, 0xb6, 0x8d, 0xdc, 0xee, 0xb0, 0xcb, 0x92, 0x47, 0xc9, 0xe3, 0x65, 0x31,
	0x8f, 0x95, 0x0d, 0x76, 0xec, 0x21, 0x2c, 0x8c, 0x6d, 0xbe, 0x08, 0x8f, 0xa1, 0x9f, 0x86, 0x3e,
	0x50, 0x69, 0x83, 0x1d, 0x2f, 0x60, 0xf5, 0x4a, 0x59, 0xdd, 0xb6, 0x57, 0xa8, 0x7c, 0x81, 0x52,
	0xdb, 0x8a, 0x1d, 0x43, 0xaa, 0x1c, 0x9d, 0x95, 0x2a, 0x17, 0xb4, 0xa4, 0xd9, 0x54, 0xc9, 0x5e,
	0xfb, 0x75, 0x36, 0x89, 0xda, 0xaf, 0x83, 0xce, 0xb3, 0x1b, 0xa4, 0x73, 0xbe, 0x83, 0xe3, 0x0b,
	0xab, 0x75, 0xfd, 0xb6, 0x7e, 0xb7, 0x97, 0x12, 0x9d, 0x63, 0x77, 0x60, 0xea, 0xd1, 0x5e, 0xe5,
	0x74, 0x68, 0x14, 0x43, 0xf5, 0x8c, 0x8e, 0x8e, 0x62, 0xa8, 0x9e, 0x93, 0x41, 0x14, 0xec, 0x3e,
	0x1c, 0x95, 0x6d, 0xa3, 0xaa, 0xed, 0x37, 0x32, 0x9a, 0x05, 0xf9, 0x89, 0x7f, 0x4f, 0x60, 0x41,
	0x6e, 0xaf, 0x45, 0xd3, 0x5e, 0x83, 0x15, 0x55, 0x9f, 0x92, 0x51, 0x14, 0x07, 0x00, 0x91, 0x4d,
	0x47, 0x00, 0x2f, 0x0e, 0x8d, 0x32, 0x9b, 0x8d, 0x1a, 0x2f, 0xf9, 0x09, 0x2c, 0x3e, 0x98, 0x4a,
	0x78, 0x7c, 0xaf, 0x77, 0xa8, 0xd8, 0x12, 0x12, 0x41, 0x50, 0x89, 0xe8, 0x55, 0x49, 0x30, 0x49,
	0xc9, 0x35, 0xb0, 0x71, 0x0a, 0xce, 0x68, 0xe5, 0xf0, 0x6f, 0x39, 0xc8, 0xf5, 0x90, 0x83, 0x0c,
	0xf7, 0x2e, 0xf3, 0x21, 0x07, 0x99, 0xb3, 0x13, 0x98, 0x9a, 0xfe, 0x26, 0x02, 0xf8, 0xe2, 0xec,
	0xf6, 0x69, 0xff, 0x6c, 0x7e, 0x4f, 0xa2, 0x88, 0x3b, 0xf8, 0x33, 0xb8, 0xfb, 0x11, 0x6d, 0x53,
	0x77, 0x17, 0xc2, 0xb9, 0xaf, 0xda, 0x56, 0x05, 0x7e, 0xde, 0xa3, 0xf3, 0xff, 0xf3, 0xe4, 0x3f,
	0x12, 0xb8, 0xf7, 0xe7, 0x24, 0xe1, 0xae, 0x60, 0x62, 0x31, 0xce, 0xde, 0x2c, 0xfa, 0x25, 0x01,
	0xa6, 0xbf, 0x00, 0x9f, 0xc3, 0xad, 0x60, 0xbf, 0x75, 0x91, 0x26, 0xb0, 0xff, 0x03, 0x74, 0x19,
	0x76, 0x0e, 0x0f, 0xe8, 0x09, 0x40, 0x9c, 0xac, 0x45, 0xd3, 0xd2, 0xf7, 0xad, 0xc6, 0x63, 0x7d,
	0xf6, 0xc5, 0x3c, 0xec, 0xe9, 0x97, 0xe5, 0x2c, 0xfc, 0x2e, 0xe7, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0xea, 0xc1, 0xf6, 0x3b, 0x03, 0x00, 0x00,
}
